title: "AlphaFold Blog"
name: "Radu Savancea"
description: "Deep learning and protein structure prediction"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"

author:
  name: "Radu Savancea"
  bio: "Exploring deep learning, scientific AI, and a world with more bits than atoms"
  location: "Stuttgart"
  avatar: "/assets/images/profile.png"

  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/radusavancea"

    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/radu-mihai-savancea-6a653826b/"
    
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:st195720@stud.uni-stuttgart.de"

markdown: kramdown
highlighter: rouge

# Enable math for Minimal Mistakes
enable_math: true


head_scripts:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js
